package com.ifechukwu.deviceguard.utils

/**
 * @Author: ifechukwu.udorji
 * @Date: 12/31/2024
 */
object Constants {
    const val COMMAND_LOCK = "LOCK"
    const val COMMAND_WIPE = "WIPE"
    const val COMMAND_REBOOT = "REBOOT"
    const val COMMAND_DISABLE_ADMIN = "DISABLE_ADMIN"
    const val COMMAND_RESET_PASSWORD = "RESET_PASSWORD"
    const val COMMAND_KIOSK_MODE = "KIOSK_MODE"
    const val COMMAND_DISABLE_SCREEN_CAPTURE = "DISABLE_SCREEN_CAPTURE"
    const val COMMAND_LOCK_SCREEN_INFO = "LOCK_SCREEN_INFO"
    const val COMMAND_SHORT_SUPPORT_MESSAGE = "SHORT_SUPPORT_MESSAGE"
    const val COMMAND_LONG_SUPPORT_MESSAGE = "LONG_SUPPORT_MESSAGE"
    const val COMMAND_LOCK_WALLPAPER = "LOCK_WALLPAPER"
    const val COMMAND_SUSPEND_APPS = "SUSPEND_APPS"
    const val COMMAND_BLOCK_UNKNOWN_SOURCES = "BLOCK_UNKNOWN_SOURCES"
}